### ISSUE TITLE
RateMe is asking me to rate even when I have already rated.

### ISSUE THREAD

**Issue by Aitorbj** [myflashlab/RateMe-ANE#1]
Hi, I checked this in Android. I know in iOS you can choose if you want users to be asked to rate with new versions, but I don't want this behavior in Android. Could it be this happening because I only voted in my rate, but I didn't write any comment?

Thanks a lot.

**Comment by myflashlab** [comment]
This ANE is now opensourced. If you need our professional help, [check here](https://github.com/myflashlab/RateMe-ANE/#tech-support)
