### ISSUE TITLE
Submit button is disabled in debug mode.

### ISSUE THREAD

**Issue by idzdigital** [myflashlab/RateMe-ANE#2]
## Environment ##
* Android API Version:
* iOS Version: 11.4
* AIR SDK Version: 29.0.0.122

## Problem Description ##
Trying to rate . Stars dialog appears and when we click on stars submit button is still disabled. How can we solve this issue?

**Comment by myflashlab** [comment]
can you relate this? https://stackoverflow.com/questions/45057452/why-the-skstorereviewcontroller-does-not-let-me-submit-a-review

**Comment by idzdigital** [comment]
Thanks for replying. So it isn't an error but will only be available to live users. got it.
